### ISSUE TITLE
java.lang.NoSuchMethodError after upgrade to version 6.1.1

### ISSUE THREAD

**Issue by falkmarcus** [joinfaces/joinfaces#3603]
After upgrade to 6.1.1 i get the following error, in a primefaces project:

```
Caused by: java.lang.NoSuchMethodError: com/sun/faces/facelets/tag/faces/ComponentSupport.addToDescendantMarkIdCache(Ljakarta/faces/component/UIComponent;Ljakarta/faces/component/UIComponent;)V (loaded from jar:nested:/cportal.war/!WEB-INF/lib/jakarta.faces-4.1.12.jar!/ by org.springframework.boot.loader.launch.LaunchedClassLoader@c0163a04) called from class jakarta.faces.component.UIComponentBase$ChildrenList (loaded from jar:nested:/cportal.war/!WEB-INF/lib/jakarta.faces-api-4.1.2.jar!/ by org.springframework.boot.loader.launch.LaunchedClassLoader@c0163a04).
```

this seems to be related in upgrading jakarta.faces from 4.1.9 to 4.1.12
